### ISSUE TITLE
default_defer_time no function?

### ISSUE THREAD

**Issue by BlackKite84** [shinsenter/defer.php#22]
The time is not set

**Comment by shinsenter** [comment]
What did you mean "the time"?

**Comment by BlackKite84** [comment]
sorry,

this Option

$defer->default_defer_time    = 100;

i have set ist to 3000 not effect

**Comment by shinsenter** [comment]
There is almost no visual difference between 100ms and 3s.
You can use browser's Developer Tool (press F12 key) to watch how requests are sent, and see the difference in Waterfall graph.
