### ISSUE TITLE
Some Errors

### ISSUE THREAD

**Issue by BlackKite84** [shinsenter/defer.php#23]
Wenn i User this page

https://community.woltlab.com with test page (Download https://www.woltlab.com/apps/)

https://github.com/shinsenter/defer.php/blob/master/test/test.php

Some Javascripts broken, diferent option i chose

**Comment by shinsenter** [comment]
Sorry @BlackKite84, I didn't get your point of the problem.
Could you please send me the set of options your are using?

The test script `https://github.com/shinsenter/defer.php/blob/master/test/test.php` is used for development process and cannot be used on your website. Please follow the usage guidline in README.md file.

https://github.com/shinsenter/defer.php/blob/master/README.md#how-to-use

**Comment by BlackKite84** [comment]
After last Update not Problems

**Comment by shinsenter** [comment]
Thanks for your feedbacks
