### ISSUE TITLE
NORMALIZE_XPATH bug?

### ISSUE THREAD

**Issue by BlackKite84** [shinsenter/defer.php#32]
this code

`<p>Na was machst du den hier, Möchtest du den Boss, Chef, Gott usw. des Forum mal genauer betrachten oder haste einfach Interesse an meiner Person und Persönlichkeit?<br><br>Naja dann wünsche ich dir Viel Spaß und hoffe deine Träume erfüllt mein Profile <img src="https://www.cafe-anime.de/_OLD/wcf/images/smilies/wink.png" alt=";)"></p>`

after minifyOutputHTML
`<p>Na was machst du den hier, Möchtest du den Boss, Chef, Gott usw. des Forum mal genauer betrachten oder haste einfach Interesse an meiner Person und Persönlichkeit?<br><br> Naja dann wünsche ich dir Viel Spaß und hoffe deine Träume erfüllt mein Profile<img alt=";)" class="defer-lazied defer-loaded" data-src="https://www.cafe-anime.de/_OLD/wcf/images/smilies/wink.png" src="https://www.cafe-anime.de/_OLD/wcf/images/smilies/wink.png" data-lazied="IMG"><noscript><img src="https://www.cafe-anime.de/_OLD/wcf/images/smilies/wink.png" alt=";)" class="jsResizeImage"></noscript></p>`

after "Profile<" is a space missing

or

`<p><strong>Avatar (<a href="https://www.cafe-anime.de/index.php?thread/17375-10-jahre-cafe-anime-cafe-anime-feiert-geburtstag/&amp;postID=514919#post514919">Vorlage</a>) by <a href="https://www.cafe-anime.de/index.php?user/5183-blacksad/">Blacksad</a>, Danke</strong></p>`

after
`<p><strong>Avatar (<a href="https://www.cafe-anime.de/index.php?thread/17375-10-jahre-cafe-anime-cafe-anime-feiert-geburtstag/&amp;postID=514919#post514919">Vorlage</a> ) by<a href="https://www.cafe-anime.de/index.php?user/5183-blacksad/">Blacksad</a>, Danke</strong></p>`

by "by<a" missing space

**Comment by shinsenter** [comment]
@BlackKite84 I found the problem in my logic. I'll fix this. Thank you for the feedback.

**Comment by shinsenter** [comment]
@BlackKite84 Please update to the latest version of the plugin. 
To archive better result, please disable lazyload and HTML-CSS-JS optimizations by other plugins.
Hope it fixes your issues.
