### ISSUE TITLE
Uncaught Error: Call to a member function get()

### ISSUE THREAD

**Issue by BlackKite84** [shinsenter/defer.php#35]
On My Framework what i use

> Fatal error: Uncaught Error: Call to a member function get() on null in C:\xampp\htdocs\wcs\lib\system\api\defer.php\src\Defer.php:211 Stack trace: #0 C:\xampp\htdocs\wcs\lib\system\api\defer.php\src\Defer.php(78): shinsenter\Defer->nodefer() #1 C:\xampp\htdocs\wcs\lib\system\event\listener\OutputModListener.class.php(57): shinsenter\Defer->fromHtml('\r\n\r\n\r\n<!DOCTYPE...') #2 C:\xampp\htdocs\wcs\lib\system\event\EventHandler.class.php(221): wcf\system\event\listener\OutputModListener->execute('wcf\\util\\Header...', 'wcf\\util\\Header...', 'parseOutput', Array) #3 C:\xampp\htdocs\wcs\lib\util\HeaderUtil.class.php(140): wcf\system\event\EventHandler->fireAction('wcf\\util\\Header...', 'parseOutput') #4 [internal function]: wcf\util\HeaderUtil::parseOutput('\r\n\r\n\r\n<!DOCTYPE...', 9) #5 C:\xampp\htdocs\wcs\lib\system\WCF.class.php(191): ob_end_flush() #6 [internal function]: wcf\system\WCF::destruct() #7 {main} thrown in C:\xampp\htdocs\wcs\lib\system\api\defer.php\src\Defer.php on line 211

i musst change teh Follow Line https://github.com/shinsenter/defer.php/blob/master/src/Defer.php#L211 to
        $has_nodefer = 0;

**Comment by shinsenter** [comment]
Can you send me the results of running belows command on your server?

php -v
php -m

**Comment by shinsenter** [comment]
@BlackKite84 
The issue was fixed in version 1.0.11:
https://github.com/shinsenter/defer.php/tree/1.0.11

**Comment by BlackKite84** [comment]
Same Problem.

The framework change ob_end_flush himself
https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/util/HeaderUtil.class.php#L140

https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/WCF.class.php#L191

Local Information (Online not Available shared Hoster)
php- v
> PHP 7.3.0 (cli) (built: Dec  6 2018 02:17:00) ( ZTS MSVC15 (Visual C++ 2017) x86 )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies

php -m
> [PHP Modules]
> bcmath
> bz2
> calendar
> Core
> ctype
> curl
> date
> dom
> exif
> fileinfo
> filter
> ftp
> gd
> gettext
> hash
> iconv
> json
> libxml
> mbstring
> mysqli
> mysqlnd
> openssl
> pcre
> PDO
> pdo_mysql
> pdo_sqlite
> Phar
> readline
> Reflection
> session
> SimpleXML
> SPL
> standard
> tokenizer
> wddx
> xml
> xmlreader
> xmlwriter
> zip
> zlib
> 
> [Zend Modules]

**Comment by BlackKite84** [comment]
ps paypal for Coffee? and what currency (direct link?)
