### ISSUE TITLE
found a Broken Script

### ISSUE THREAD

**Issue by BlackKite84** [shinsenter/defer.php#36]
I have found a Script thats Broken all (No Console Error)

Before
![001](https://user-images.githubusercontent.com/3486554/56514957-f97f0000-6536-11e9-8442-ef66a2b20bf7.PNG)
Code-> https://paste.ee/p/ePXqY

After
![002](https://user-images.githubusercontent.com/3486554/56515048-3cd96e80-6537-11e9-8b59-06e1a931edb1.PNG)
Code-> https://paste.ee/p/aThOO

Setting
>			// Library injection
>			$defer->append_defer_js     = true;
>			$defer->default_defer_time  = 10;
>
>			// Page optimizations
>			$defer->enable_preloading   = false;
>			$defer->enable_dns_prefetch = false;
>			$defer->fix_render_blocking = false;
>			$defer->minify_output_html  = false;
>
>			// Tag optimizations
>			$defer->enable_defer_css        = false;
>			$defer->enable_defer_scripts    = false;
>			$defer->enable_defer_images     = false;
>			$defer->enable_defer_iframes    = false;
>			$defer->enable_defer_background = false;
>			$defer->enable_defer_fallback   = false;
>
>			// Web-font optimizations
>			$defer->defer_web_fonts = false;
>
>			// Image and iframe placeholders
>			$defer->empty_gif               = '';
>			$defer->empty_src               = '';
>			$defer->use_color_placeholder   = false;
>			$defer->use_css_fadein_effects  = false;
>
>			// Blacklist
>			$defer->do_not_optimize = [
>				'document\.write\s*\(',
>				'(jquery([-_][\d\.]+)?(\.min)?\.js|jquery-core)',
>				'partner',
>				'styleLogo'
>			];

**Comment by shinsenter** [comment]
Thank you. I will improve that in the next version

**Comment by shinsenter** [comment]
@BlackKite84 
The issue was fixed in version 1.0.11:
https://github.com/shinsenter/defer.php/tree/1.0.11
