### ISSUE TITLE
Google Chrome to support lazy loading by default, starting with version 75

### ISSUE THREAD

**Issue by BlackKite84** [shinsenter/defer.php#40]
Some Informations for Future

https://stadt-bremerhaven.de/lazy-loading-fuer-bilder-google-chrome-75-soll-das-feature-integrieren/

https://www.androidpolice.com/2019/04/08/google-chrome-to-support-lazy-loading-by-default-starting-with-version-75/

https://addyosmani.com/blog/lazy-loading/

https://www.xda-developers.com/google-chrome-image-lazy-loading-speed-up-page-loading-mobile/

**Comment by shinsenter** [comment]
@BlackKite84 Thank you. Great updates!
