### ISSUE TITLE
How do use width smarty template ?

### ISSUE THREAD

**Issue by bratsadlove** [shinsenter/defer.php#45]
Hi !

My project using smarty template engine it's synax bellow

require_once(SMARTY_DIR . 'Smarty.class.php');

$smarty = new Smarty();

$smarty->setTemplateDir('/web/www.example.com/guestbook/templates/');
$smarty->setCompileDir('/web/www.example.com/guestbook/templates_c/');
$smarty->setConfigDir('/web/www.example.com/guestbook/configs/');
$smarty->setCacheDir('/web/www.example.com/guestbook/cache/');

$smarty->assign('name','Ned');

//** un-comment the following line to show the debug console
//$smarty->debugging = true;

$smarty->display('index.tpl');

it's display through display function but shinsenter not like that it's output direct

**Comment by shinsenter** [comment]
### Optimize output HTML for your website

You can capture the output that is generated by PHP, and optimize the output with defer.php, like this:
```php
// Include the library 
require_once __DIR__ . '/vendor/shinsenter/defer.php/defer.php'; 

// Create a function for output optimization 
function deferjs_optimization($html) { 
// Create a Defer object 
$defer = new \shinsenter\Defer(); 
// Then get the optimized output 
return $defer->fromHtml($html)->toHtml(); 
} 
// Turn output buffering on with ob_start 
// Run this before HTML rendering 
ob_start('deferjs_optimization'); 

// .......... (other PHP stuffs here) 
$smarty->display('index.tpl');

// And call this to flush optimized output HTML 
// right before you send the HTML to browser 

ob_end_flush();
```

**Comment by bratsadlove** [comment]
Hi !

This show error:

Parse error: syntax error, unexpected '.', expecting ',' or ';' in  src/DeferInterface.php on line 79

**Comment by shinsenter** [comment]
Oops. I'm sorry about that.
Which version are you using?

**Comment by bratsadlove** [comment]
I'm get today

**Comment by shinsenter** [comment]
This library requires PHP >= 5.6. It may not support your PHP version.

**Comment by bratsadlove** [comment]
> This library requires PHP >= 5.6. It may not support your PHP version.

Great ! I will update PHP version. 
Thank's
