### ISSUE TITLE
Plugin does not work properly with caching (non-optimized version gets saved)

### ISSUE THREAD

**Issue by redlet** [shinsenter/defer.php#53]
I think I posted this in the wrong github repo--I was sent to the defer.js one. Anyway, for some reason your optimized output does not get saved in the Cache Enabler cache. The author of Autoptimize says `AO uses output buffering in order not to depend on any caching plugin.` 

Is it possible you could use this technique so yours gets cached, too? I prefer your plugin.

**Comment by shinsenter** [comment]
Dear @redlet 

Thank you for using my library, and for mentioning this issue (I think it would be better if it was posted in repo defer-wordpress). I do not understand how WordPress Cache works, so I still can't get a satisfactory answer to your question right now. I will find more information about it and reply to you later.

**Comment by redlet** [comment]
@shinsenter I am so sorry for posting in the wrong place and thank you for responding. 

Your plugin suggests at the top to use a cache and "Cache Enabler" (this is the name of the plugin) supports WebP images so I have to use that plugin. I look forward to your response later.

**Comment by shinsenter** [comment]
@redlet 

I think I need some html output (current state and what you expect) from your site to analyze and find ways to improve my library in future updates.

**Comment by redlet** [comment]
@shinsenter This is expected: https://pastebin.com/QDCmTbwj
As you can see, it is optimized and includes: 
```
<!--
   ┌┬┐┌─┐┌─┐┌─┐┬─┐  ┬┌─┐
    ││├┤ ├┤ ├┤ ├┬┘  │└─┐
   ─┴┘└─┘└  └─┘┴└─o└┘└─┘
This page was optimized with defer.js
https://wordpress.org/plugins/shins-pageload-magic/
-->
```
This is what gets cached and served to clients after the first visit generates the cache:
https://pastebin.com/Gm2MpZ7w
You can see it is cached by Cache Enabler:
```
<!-- Cache Enabler by KeyCDN @ 15.04.2020 16:11:34 (webp) -->
```
This cache does *not* include your optimizations. 

Edit: Here is the cache plugin I am using: https://github.com/keycdn/cache-enabler

**Comment by redlet** [comment]
I just want to mention, another plugin I use (WebP Express) modifies HTML with "output buffering" as well. This seems to be the way to do it, but I am not sure what output buffering entails. I hope this helps.

**Comment by redlet** [comment]
I tried Autoptimize and it is compatible with my cache, but it was not as fast as your plugin. So I'll just have to wait. :stuck_out_tongue:

**Comment by redlet** [comment]
@shinsenter Any updates?

**Comment by shinsenter** [comment]
@redlet 
I am reviewing how Cache Enabler works. But there still no solution for that.

**Comment by redlet** [comment]
@shinsenter You can look at the concept of "output buffering" as it is used in WebP Express as well:

https://github.com/rosell-dk/webp-express/search?q=output+buffer&unscoped_q=output+buffer

You can see there's an "add_filter" function call with a priority; I'm not sure if this helps but it looks relevant.

**Comment by shinsenter** [comment]
@redlet 

Thanks for your suggestion. 
I'm not sure after changing plugin hooks' priority, your webp plugin will work correctly. My plugin will convert the img attribute of the img tags to other attributes, this can make it impossible for other plugins to properly parse image URLs. So my plugin should do the final part with the final HTML output of all other plugins.

Unfortunately, it seems there is a plugin that ended up processing it itself and exporting the HTML content to the client, before the optimization process of my plugin started.

**Comment by redlet** [comment]
Yes, you're right; I just realized a potential issue. Cache Enabler rewrites the `img` tags and it is always the final step. (It saves a cached PNG/JPEG copy and a cached WEBP copy).

Autoptimize is able to optimize HTML and still work with Cache Enabler, however. Hopefully you're able to find a solution.

**Comment by redlet** [comment]
@shinsenter nothing eh?

**Comment by redlet** [comment]
Still hoping for this to get resolved. It would help a lot for the optimized HTML to be cached.

**Comment by redlet** [comment]
:(

**Comment by shinsenter** [comment]
Working on v2.0

**Comment by shinsenter** [comment]
@redlet You can try v2.0-beta
