### ISSUE TITLE
[Bug] Doesn't work on php5.6, codeigniter 3

### ISSUE THREAD

**Issue by anhvandev** [shinsenter/defer.php#67]
Hi I have tested your project on my Codeigniter source code.

Wow it changed the html code structure amazingly. But there was a problem. I think it is caused by your defer.js component. It makes all image and js resources unloadable.

Best regards and good luck!

**Comment by shinsenter** [comment]
Hi @anhvandev 
Bạn có thể cho mình thêm thông tin về cách bạn implement thư viện và lỗi gặp phải không?

**Comment by anhvandev** [comment]
> Hi @anhvandev Bạn có thể cho mình thêm thông tin về cách bạn implement thư viện và lỗi gặp phải không?

@shinsenter 
Để mình setup lại rồi gửi bạn nhé

**Comment by anhvandev** [comment]
@shinsenter 
- Bước 1: Đầu tiên mình cài gói bằng composer.
- Bước 2:
> Sau đó setup hook như thế này:

![image](https://user-images.githubusercontent.com/49545158/141680037-a747ea45-c97f-4586-a676-be4085cb6273.png)
> Nội dung file Defer.php:
![image](https://user-images.githubusercontent.com/49545158/141680200-83cc69ed-99f6-4225-9447-e10435ef3672.png)
- Bước 3: chuyển thử một số thẻ img về ban đầu để xem thư viện chuyển đổi
- Bước 4: Xem thử kết quả:
> Ảnh
![image](https://user-images.githubusercontent.com/49545158/141680290-a8442cac-2ec1-4104-82cf-6d2fb3f91b9d.png)
![image](https://user-images.githubusercontent.com/49545158/141680465-42145715-8aea-40c7-b1ab-a35a05c98944.png)
> Script:
![image](https://user-images.githubusercontent.com/49545158/141680410-fdee5fb1-99c1-4664-83ec-4351c47e8ed4.png)
> Network All:
![image](https://user-images.githubusercontent.com/49545158/141680324-0167e059-83b5-43ad-9c39-dd0a9f388b0c.png)

**Comment by shinsenter** [comment]
@anhvandev 
Cảm ơn bạn vì thông tin, có vẻ như PHP5.6 không phải vấn đề trong setup của bạn.

Ngoài ra thư viện defer.js hình như chưa được load dẫn đến tình trạng này, thực sự trong mô tả của bạn không chụp phần này nên mình cũng khó phán đoán.

Bạn có thể mở cho mình đường link đến website staging và đang bật defer.js để mình inspect thêm không?

**Comment by anhvandev** [comment]
> @anhvandev Cảm ơn bạn vì thông tin, có vẻ như PHP5.6 không phải vấn đề trong setup của bạn.
> 
> Ngoài ra thư viện defer.js hình như chưa được load dẫn đến tình trạng này, thực sự trong mô tả của bạn không chụp phần này nên mình cũng khó phán đoán.
> 
> Bạn có thể mở cho mình đường link đến website staging và đang bật defer.js để mình inspect thêm không?

Mình đã thấy thư viện defer,js đã được inject vào head. Mình ko public source code lên đc mong bạn thông cảm

**Comment by shinsenter** [comment]
@anhvandev 
Cho mình hỏi thêm bạn có đang dùng framework nào render các element cho frontend (như VueJS, ReactJS, Angular v.v..) hay không? Hoặc các thẻ hình của bạn có được khởi tạo bằng javascript (bao gồm cả AJAX, tạo DOM trong quá trình render trang web) hay không?
Do thư viện defer.js không tự trigger cho các thẻ được khởi tạo dạng này. Nếu website của bạn tạo động UI bằng JS thì bạn không cần quan tâm tới việc sử dụng các thư viện lazyload nữa.

**Comment by anhvandev** [comment]
> @anhvandev Cho mình hỏi thêm bạn có đang dùng framework nào render các element cho frontend (như VueJS, ReactJS, Angular v.v..) hay không? Hoặc các thẻ hình của bạn có được khởi tạo bằng javascript (bao gồm cả AJAX, tạo DOM trong quá trình render trang web) hay không? Do thư viện defer.js không tự trigger cho các thẻ được khởi tạo dạng này. Nếu website của bạn tạo động UI bằng JS thì bạn không cần quan tâm tới việc sử dụng các thư viện lazyload nữa.

như mình chụp thì là render hoàn toàn bằng php thôi ko dùng js đâu bạn.

**Comment by shinsenter** [comment]
@anhvandev 
Một lần nữa, thực sự rất khó để phán đoán nếu ko có đầy đủ thông tin. Mình có thể xin HTML output của website của bạn trước khi apply defer.php hay không?

**Comment by anhvandev** [comment]
> @anhvandev Một lần nữa, thực sự rất khó để phán đoán nếu ko có đầy đủ thông tin. Mình có thể xin HTML output của website của bạn trước khi apply defer.php hay không?

mình gửi bạn nhé
[before.txt](https://github.com/shinsenter/defer.php/files/7535677/before.txt)
[after.txt](https://github.com/shinsenter/defer.php/files/7535679/after.txt)

**Comment by shinsenter** [comment]
@anhvandev 
Mình xem HTML trong [after.txt](https://github.com/shinsenter/defer.php/files/7535679/after.txt) thì thấy `<script id="defer-js"></script>` đoạn này bị rỗng, bên trong đáng lẽ ra phải embed thư viện defer.js mới đúng.

Trong options của bạn không set cho tùy chọn `deferjs_src`, mặc định nó sẽ download file từ `https://cdn.jsdelivr.net/npm/@shinsenter/defer.js@2.5.0/dist/defer_plus.min.js` về và cache lại. Có vẻ lúc đó server của bạn đã không thể download được file này và cache một nội dung rỗng.

Bạn thử giúp mình download `defer_plus.min.js` từ đường link trên, lưu trên cùng thư mục với file `Defer.php` của bạn, và trong option của thư viện, giúp mình dẫn để tập tin ở local xem sao nhé!

```php
<?php
// ....
$options = [
    'debug_mode' => false,
    'deferjs_src'  => __DIR__ . '/defer_plus.min.js',
];
$defer  = new \AppSeeds\Defer($options);
```

**Comment by anhvandev** [comment]
> @anhvandev Mình xem HTML trong [after.txt](https://github.com/shinsenter/defer.php/files/7535679/after.txt) thì thấy `<script id="defer-js"></script>` đoạn này bị rỗng, bên trong đáng lẽ ra phải embed thư viện defer.js mới đúng.
> 
> Trong options của bạn không set cho tùy chọn `deferjs_src`, mặc định nó sẽ download file từ `https://cdn.jsdelivr.net/npm/@shinsenter/defer.js@2.5.0/dist/defer_plus.min.js` về và cache lại. Có vẻ lúc đó server của bạn đã không thể download được file này và cache một nội dung rỗng.
> 
> Bạn thử giúp mình download `defer_plus.min.js` từ đường link trên, lưu trên cùng thư mục với file `Defer.php` của bạn, và trong option của thư viện, giúp mình dẫn để tập tin ở local xem sao nhé!
> 
> ```
> <?php
> // ....
> $options = [
>     'debug_mode' => false,
>     'deferjs_src'  => __DIR__ . '/defer_plus.min.js',
> ];
> $defer  = new \AppSeeds\Defer($options);
> ```

ok thank bạn nha
