### ISSUE TITLE
Got Warning Deprecated

### ISSUE THREAD

**Issue by Iquaridys** [shinsenter/defer.php#68]
Deprecated: Return type of AppSeeds\Elements\DocumentNode::normalize() should either be compatible with DOMNode::normalize(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in \vendor\shinsenter\defer.php\src\Elements\DocumentNode.php on line 272

Deprecated: DOMDocument::createElement(): Passing null to parameter #2 ($value) of type string is deprecated in \vendor\shinsenter\defer.php\src\Elements\DocumentNode.php on line 197

how to fix it?

**Comment by shinsenter** [comment]
Hey @Iquaridys 

Thank you for using this library and leaving feedback. Due to me not maintaining this library for a while, it doesn't support well for PHP versions from 8.0. I will try to update it and inform you when I have time.

Regards.

**Comment by shinsenter** [comment]
Hey @Iquaridys

I have fixed the issues of the library related to PHP 8.x versions.
Please try using composer to install the library with the "dev-master" version, and please give me feedback on whether your issue has been resolved.

https://packagist.org/packages/shinsenter/defer.php#dev-master

Best regards.

**Comment by theperfectwill** [comment]
@shinsenter 

> I have fixed the issues of the library related to PHP 8.x versions. Please try using composer to install the library with the "dev-master" version, and please give me feedback on whether your issue has been resolved.

Hi. I have tried this version in the latest PHP 8.x versions and did not find this error, so I thought I would just reply about it, so that you might close it as well, if you wanted to.

**Comment by shinsenter** [comment]
@theperfectwill Thank you for the information. I will close this issue.
