### ISSUE TITLE
Testing with Dev Master (v2.5)

### ISSUE THREAD

**Issue by theperfectwill** [shinsenter/defer.php#69]
Hi. 

I am using this version `Dev Master (v2.5)` and got it all working. 

I am using it in relation to Wordpress.

So if you have some updates you want to `push`, or `mention`, or `test`, feel free to let me know :) and I'll give it a run.

**Comment by shinsenter** [comment]
@theperfectwill Wow, thank you so much for the kind offer. I truly appreciate it. When I release some bug fixes, I may need a tester to help me double-check in case I accidentally change something crazy.

**Comment by theperfectwill** [comment]
> When I release some bug fixes, I may need a tester to help me double-check in case I accidentally change something crazy.

Ok, cool.

I have found 2 issues, but trying to figure out is it from one issue or combination of two. I mean the issue seems to be a combination of enable_preload and fix_render_blocking.

I started writing an issue about it, but I will dig more into it first.

**Comment by shinsenter** [comment]
@theperfectwill 
OK I got it!
I'll hold off on releasing v2.5 for now until I can assess whether the issues you ran into can be swiftly resolved or not.

**Comment by theperfectwill** [comment]
@shinsenter 

> I'll hold off on releasing v2.5 for now until I can assess whether the issues you ran into can be swiftly resolved or not.

Ok.

Well I can tell you one issue I have found but need to test more, but it may be something you can spot easier.

If the script tag has a src attribute, and an id attribute, then that script will not be preloaded when enable_preload is true.

I'm working with WordPress and most scripts have an id attribute in the script tag, so then most scripts in Wordpress are not preloaded when enable_preload is true.

Can you confirm that is an issue? 

...

The other issue is what I have to test some more. I sometimes end up with double the output in the head tag.

**Comment by shinsenter** [comment]
@theperfectwill 
Could you please provide me with an example of the HTML before it has been optimized by this library? I need the exact HTML content you are having trouble with.
